### ISSUE TITLE
项目编译的一些问题

### ISSUE THREAD

**Issue by gkj17** [junfengren/PinyinIME#1]
请问一下junren哥，我在[这里](https://github.com/lizhangqu/PinyinIME/issues/1)遇到同类问题后，来到了你的项目，我导入as后，运行提示是：
Unable to make field private static final java.util.Map java.lang.ProcessEnvironment.theCaseInsensitiveEnvironment accessible: module java.base does not "opens java.lang" to unnamed module @3e57cd70

这应该怎么办呀，我的as版本是：【Android Studio Flamingo | 2022.2.1 Patch 2】

**Comment by fengjunren** [comment]
clean project 试下看
这个项目是jdk  1.8的，看下版本

**Comment by fengjunren** [comment]
我下载最新的as , 改AGP和Gradle 版本，clean project 后编译也成功了

![2024-01-07_153135](https://github.com/fengjunren/PinyinIME/assets/18107765/00c71995-5f90-4ca8-8fe8-c0562a3dc3ca)

**Comment by gkj17** [comment]
感谢junren哥，可以了！
